version: '3'

services:
  bot:
    container_name: peon
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/database.sqlite:/bot/db/database.sqlite
    env_file: .env
    restart: unless-stopped
